In [1]:
import sys
import os
sys.path.append(r"C:\Users\Admin\Desktop\GroupX_DataAnalysis\NDTA631-DataAnalysis-GroupX\scripts")
import pandas as pd
from data_pipeline import load_data, clean_data, filter_south_africa_data

df1 = load_data(r"C:\Users\Admin\Desktop\GroupX_DataAnalysis\NDTA631-DataAnalysis-GroupX\data\raw\employment.csv ", 'employment')
df2 = load_data(r"C:\Users\Admin\Desktop\GroupX_DataAnalysis\NDTA631-DataAnalysis-GroupX\data\raw\poverty.csv", 'poverty')

df1_clean = clean_data(df1, 'employment')
df2_clean = clean_data(df2, 'poverty')

df1_filter = filter_south_africa_data(df1_clean, "REF_AREA_LABEL", "employment_sa_clean")
df2_filter = filter_south_africa_data(df2_clean, "REF_AREA_LABEL", "poverty_sa_clean")

if df1_filter is not None and df2_filter is not None:
    print("Descriptive Statistics for employment:")
    print(df1_clean.describe())
    print("\nDescriptive Statistics for poverty:")
    print(df2_clean.describe())
    print("\nMissing Values in employment:", df1_clean.isnull().sum())
    print("\nMissing Values in poverty:", df2_clean.isnull().sum())
else:
    print("Error: Could not load or clean datasets.")

2025-09-02 23:15:02,929 - INFO - Loaded employment with 242 rows
2025-09-02 23:15:02,944 - INFO - Loaded poverty with 1050 rows
2025-09-02 23:15:02,945 - INFO - Cleaning employment, initial shape: (242, 86)
2025-09-02 23:15:02,988 - INFO - Cleaned employment, final shape: (242, 86)
2025-09-02 23:15:02,990 - INFO - Cleaning poverty, initial shape: (1050, 45)
2025-09-02 23:15:03,018 - INFO - Cleaned poverty, final shape: (1050, 45)

Descriptive Statistics for employment:
       DECIMALS  UNIT_MULT        1960        1961        1962        1963  \
count     242.0      242.0  242.000000  242.000000  242.000000  242.000000
mean        2.0        0.0   60.079000   59.640333   59.482000   59.010000
std         0.0        0.0    0.627829    0.669063    0.628302    0.569606
min         2.0        0.0   56.100000   55.400000   55.500000   55.400000
25%         2.0        0.0   60.079000   59.640333   59.482000   59.010000
50%         2.0        0.0   60.079000   59.640333   59.482000   59.010000
75%         2.0        0.0   60.079000   59.640333   59.482000   59.010000
max         2.0        0.0   68.037000   68.121000   67.446000   66.230000

             1964        1965        1966        1967  ...        2014  \
count  242.000000  242.000000  242.000000  242.000000  ...  242.000000
mean    58.920333   59.103333   59.583000   59.901667  ...   56.973815
std      0.508122    0.458104    0.423339    0.410505  ...    9.353023
min     55.700000   56.200000   56.900000   57.300000  ...   24.055000
25%     58.920333   59.103333   59.583000   59.901667  ...   55.563500
50%     58.920333   59.103333   59.583000   59.901667  ...   56.973815
75%     58.920333   59.103333   59.583000   59.901667  ...   59.587986
max     65.361000   64.910000   64.949000   65.105000  ...   87.120000

             2015        2016        2017        2018        2019        2020  \
count  242.000000  242.000000  242.000000  242.000000  242.000000  242.000000
mean    57.563125   57.035553   56.353007   57.066734   57.205423   55.693212
std      8.749644    8.001152    8.742712    6.993263    8.144871    7.251956
min     22.488000   24.743000   21.777000   26.188000   26.747000   25.089000
25%     56.925000   56.445521   55.985250   56.605892   55.409250   54.619250
50%     57.563125   57.035553   56.353007   57.066734   57.205423   55.693212
75%     59.302250   58.948916   59.046250   58.649361   59.991500   56.340250
max     92.440000   92.970000   88.070000   87.240000   87.880000   86.310000

             2021        2022        2023
count  242.000000  242.000000  242.000000
mean    55.408317   57.776614   58.474214
std      7.328556    7.508612    5.472265
min     27.523000   29.919000   33.456000
25%     55.393829   57.569215   58.474214
50%     55.408317   57.776614   58.474214
75%     56.997000   58.717500   58.474214
max     87.280000   95.100000   89.222000

[8 rows x 66 columns]

Descriptive Statistics for poverty:
       TIME_PERIOD    OBS_VALUE  DECIMALS  UNIT_MULT  COMMENT_OBS
count  1050.000000  1050.000000    1050.0     1050.0          0.0
mean   2013.062857    24.416952       2.0        0.0          NaN
std       5.973715    14.447124       0.0        0.0          NaN
min    2000.000000     0.000000       2.0        0.0          NaN
25%    2008.000000    14.400000       2.0        0.0          NaN
50%    2014.000000    20.550000       2.0        0.0          NaN
75%    2018.000000    29.950000       2.0        0.0          NaN
max    2024.000000    82.300000       2.0        0.0          NaN

Missing Values in employment: FREQ              0
FREQ_LABEL        0
REF_AREA          0
REF_AREA_LABEL    0
INDICATOR         0
                 ..
2019              0
2020              0
2021              0
2022              0
2023              0
Length: 86, dtype: int64

Missing Values in poverty: STRUCTURE                    0
STRUCTURE_ID                 0
ACTION                       0
FREQ                         0
FREQ_LABEL                   0
REF_AREA                     0
REF_AREA_LABEL               0
INDICATOR                    0
INDICATOR_LABEL              0
SEX                          0
SEX_LABEL                    0
AGE                          0
AGE_LABEL                    0
URBANISATION                 0
URBANISATION_LABEL           0
UNIT_MEASURE                 0
UNIT_MEASURE_LABEL           0
COMP_BREAKDOWN_1             0
COMP_BREAKDOWN_1_LABEL       0
COMP_BREAKDOWN_2             0
COMP_BREAKDOWN_2_LABEL       0
COMP_BREAKDOWN_3             0
COMP_BREAKDOWN_3_LABEL       0
TIME_PERIOD                  0
OBS_VALUE                    0
AGG_METHOD                   0
AGG_METHOD_LABEL             0
DECIMALS                     0
DECIMALS_LABEL               0
DATABASE_ID                  0
DATABASE_ID_LABEL            0
COMMENT_TS                   0
UNIT_MULT                    0
UNIT_MULT_LABEL              0
DATA_SOURCE                  0
DATA_SOURCE_LABEL            0
UNIT_TYPE                    0
UNIT_TYPE_LABEL              0
TIME_FORMAT                  0
TIME_FORMAT_LABEL            0
COMMENT_OBS               1050
OBS_STATUS                   0
OBS_STATUS_LABEL             0
OBS_CONF                     0
OBS_CONF_LABEL               0
dtype: int64

In [2]:
import sqlite3
import pandas as pd

conn = sqlite3.connect(r'C:\Users\Admin\Desktop\GroupX_DataAnalysis\NDTA631-DataAnalysis-GroupX\scripts\database.db')
df_employment = pd.read_sql('SELECT * FROM employment', conn)
df_poverty = pd.read_sql('SELECT * FROM poverty', conn)
conn.close()

print(df_employment.head())
print(df_poverty.head())

  FREQ FREQ_LABEL REF_AREA              REF_AREA_LABEL  \
0    A     Annual      ABW                       Aruba
1    A     Annual      AFG                 Afghanistan
2    A     Annual      AFW  Africa Western and Central
3    A     Annual      AGO                      Angola
4    A     Annual      ALB                     Albania

                     INDICATOR  \
0  WB_WDI_SL_EMP_TOTL_SP_NE_ZS
1  WB_WDI_SL_EMP_TOTL_SP_NE_ZS
2  WB_WDI_SL_EMP_TOTL_SP_NE_ZS
3  WB_WDI_SL_EMP_TOTL_SP_NE_ZS
4  WB_WDI_SL_EMP_TOTL_SP_NE_ZS

                                     INDICATOR_LABEL UNIT_MEASURE  \
0  Employment to population ratio, 15+, total (%)...           PT
1  Employment to population ratio, 15+, total (%)...           PT
2  Employment to population ratio, 15+, total (%)...           PT
3  Employment to population ratio, 15+, total (%)...           PT
4  Employment to population ratio, 15+, total (%)...           PT

  UNIT_MEASURE_LABEL AGG_METHOD AGG_METHOD_LABEL  ...       2014       2015  \
0         Percentage         _Z   Not Applicable  ...  56.973815  57.563125
1         Percentage         _Z   Not Applicable  ...  47.631000  57.563125
2         Percentage         _Z   Not Applicable  ...  56.973815  57.563125
3         Percentage         _Z   Not Applicable  ...  39.384000  57.563125
4         Percentage         _Z   Not Applicable  ...  43.775000  45.955000

        2016       2017       2018       2019       2020       2021  \
0  57.035553  56.353007  57.066734  57.205423  55.693212  55.408317
1  57.035553  42.015000  57.066734  57.205423  36.710000  46.906000
2  57.035553  63.101578  57.066734  56.979612  55.693212  55.408317
3  57.035553  56.353007  57.066734  62.645000  55.693212  64.306000
4  48.477000  50.152000  52.000000  53.392000  52.457000  52.836000

        2022       2023
0  57.776614  58.474214
1  57.776614  58.474214
2  72.606365  58.474214
3  64.620000  58.474214
4  55.457000  57.066000

[5 rows x 86 columns]
       STRUCTURE                STRUCTURE_ID ACTION FREQ FREQ_LABEL REF_AREA  \
0  datastructure  WB.DATA360:DS_DATA360(1.3)      I    A     Annual      BLR
1  datastructure  WB.DATA360:DS_DATA360(1.3)      I    A     Annual      BOL
2  datastructure  WB.DATA360:DS_DATA360(1.3)      I    A     Annual      CHL
3  datastructure  WB.DATA360:DS_DATA360(1.3)      I    A     Annual      CHN
4  datastructure  WB.DATA360:DS_DATA360(1.3)      I    A     Annual      SWZ

  REF_AREA_LABEL           INDICATOR  \
0        Belarus  WB_WDI_SI_POV_NAHC
1        Bolivia  WB_WDI_SI_POV_NAHC
2          Chile  WB_WDI_SI_POV_NAHC
3          China  WB_WDI_SI_POV_NAHC
4       Eswatini  WB_WDI_SI_POV_NAHC

                                     INDICATOR_LABEL SEX  ...  \
0  Poverty headcount ratio at national poverty li...  _T  ...
1  Poverty headcount ratio at national poverty li...  _T  ...
2  Poverty headcount ratio at national poverty li...  _T  ...
3  Poverty headcount ratio at national poverty li...  _T  ...
4  Poverty headcount ratio at national poverty li...  _T  ...

                    DATA_SOURCE_LABEL UNIT_TYPE UNIT_TYPE_LABEL TIME_FORMAT  \
0  World Development Indicators (WDI)     RATIO           Ratio         P1Y
1  World Development Indicators (WDI)     RATIO           Ratio         P1Y
2  World Development Indicators (WDI)     RATIO           Ratio         P1Y
3  World Development Indicators (WDI)     RATIO           Ratio         P1Y
4  World Development Indicators (WDI)     RATIO           Ratio         P1Y

  TIME_FORMAT_LABEL COMMENT_OBS OBS_STATUS OBS_STATUS_LABEL OBS_CONF  \
0            Annual        None          A     Normal value       PU
1            Annual        None          A     Normal value       PU
2            Annual        None          A     Normal value       PU
3            Annual        None          A     Normal value       PU
4            Annual        None          A     Normal value       PU

  OBS_CONF_LABEL
0         Public
1         Public
2         Public
3         Public
4         Public

[5 rows x 45 columns]